version: "3"

services:
  api:
    build: .
    command: hypercorn --bind 0.0.0.0:7000 --reload main:app
    container_name: "api"
    ports:
      - "7000:7000"
    env_file:
      - .env
    volumes:
      - ./app:/app
